/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { SnippetCodenames } from '../system/snippets.generated.js';
import type { Elements, Snippet } from '@kontent-ai/delivery-sdk';
import type { AudienceTaxonomyTermCodenames, AudienceTaxonomyCodename } from '../taxonomies/audience-taxonomy.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { OfferingsTaxonomyTermCodenames, OfferingsTaxonomyCodename } from '../taxonomies/offerings-taxonomy.generated.js';
           
            /*
* Type representing codename of 'Audience' snippet
*/
            export type AudienceSnippetCodename = keyof Pick<Record<SnippetCodenames, null>, "audience">;

            /*
* Typeguard for codename of 'Audience' snippet
*/
            export function isAudienceSnippetCodename(value: string | undefined | null): value is AudienceSnippetCodename {
                return typeof value === 'string' && value === ('audience' satisfies AudienceSnippetCodename);
            }

/*
    * Audience
    *
    * Id: 57aca260-443d-4e7a-bbb5-1f7c6744bf91
* Codename: audience
    */
export type AudienceSnippet = Snippet<AudienceSnippetElementCodenames,
{
/*
    * Audience
    *
    * Codename: audience__audience
* Id: a8dd611e-2932-405d-ace4-6274aa7afe39
* Type: taxonomy
* Required: false
* Taxonomy: audience
    */
                readonly audience__audience: Elements.TaxonomyElement<AudienceTaxonomyTermCodenames, AudienceTaxonomyCodename>;

/*
    * Offerings
    *
    * Codename: audience__offerings
* Id: 7d83f8f3-b1a3-4dbd-ac00-5f291b6445ce
* Type: taxonomy
* Required: false
* Taxonomy: offerings
    */
                readonly audience__offerings: Elements.TaxonomyElement<OfferingsTaxonomyTermCodenames, OfferingsTaxonomyCodename>;}>;

/*
* Type representing all available element codenames for Audience
*/
export type AudienceSnippetElementCodenames = 'audience__audience' | 'audience__offerings';



            