/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Academic Content' collection
*/
            export type AcademicContentCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "academic_content">;

            /*
* Typeguard for codename of 'Academic Content' collection
*/
            export function isAcademicContentCollectionCodename(value: string | undefined | null): value is AcademicContentCollectionCodename {
                return typeof value === 'string' && value === ('academic_content' satisfies AcademicContentCollectionCodename);
            }
            