/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Follett Content' collection
*/
            export type FollettContentCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "academic_content">;

            /*
* Typeguard for codename of 'Follett Content' collection
*/
            export function isFollettContentCollectionCodename(value: string | undefined | null): value is FollettContentCollectionCodename {
                return typeof value === 'string' && value === ('academic_content' satisfies FollettContentCollectionCodename);
            }
            