/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Librarian Resources' collection
*/
            export type LibrarianResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "patient_resources">;

            /*
* Typeguard for codename of 'Librarian Resources' collection
*/
            export function isLibrarianResourcesCollectionCodename(value: string | undefined | null): value is LibrarianResourcesCollectionCodename {
                return typeof value === 'string' && value === ('patient_resources' satisfies LibrarianResourcesCollectionCodename);
            }
            