/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Marketing Resources' collection
*/
            export type MarketingResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "marketing_resources">;

            /*
* Typeguard for codename of 'Marketing Resources' collection
*/
            export function isMarketingResourcesCollectionCodename(value: string | undefined | null): value is MarketingResourcesCollectionCodename {
                return typeof value === 'string' && value === ('marketing_resources' satisfies MarketingResourcesCollectionCodename);
            }
            