/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Operations' collection
*/
            export type OperationsCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "operations">;

            /*
* Typeguard for codename of 'Operations' collection
*/
            export function isOperationsCollectionCodename(value: string | undefined | null): value is OperationsCollectionCodename {
                return typeof value === 'string' && value === ('operations' satisfies OperationsCollectionCodename);
            }
            