/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Patient Resources' collection
*/
            export type PatientResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "patient_resources">;

            /*
* Typeguard for codename of 'Patient Resources' collection
*/
            export function isPatientResourcesCollectionCodename(value: string | undefined | null): value is PatientResourcesCollectionCodename {
                return typeof value === 'string' && value === ('patient_resources' satisfies PatientResourcesCollectionCodename);
            }
            