/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { ArticleType } from '../types/article-type.generated.js';
import type { BlogPostType } from '../types/blog-post-type.generated.js';
import type { CallToActionType } from '../types/call-to-action-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { CTACardType } from '../types/cta-card-type.generated.js';
import type { DisclaimerType } from '../types/disclaimer-type.generated.js';
import type { EventType } from '../types/event-type.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { VideoType } from '../types/video-type.generated.js';
import type { WebinarType } from '../types/webinar-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Landing Page' type
*/
            export type LandingPageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">;

            /*
* Typeguard for codename of 'Landing Page' type
*/
            export function isLandingPageTypeCodename(value: string | undefined | null): value is LandingPageTypeCodename {
                return typeof value === 'string' && value === ('landing_page' satisfies LandingPageTypeCodename);
            }

/*
    * Landing Page
    *
    * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
* Codename: landing_page
    */
export type LandingPageType = IContentItem<
{
/*
    * Headline
    *
    * Codename: headline
* Id: 19b37bc8-cd8a-43a2-a647-61732524abed
* Type: text
* Required: true
    */
                readonly headline: Elements.TextElement;

/*
    * Subheadline
    *
    * Codename: subheadline
* Id: 1f3be25d-1bcf-4e59-9003-14490f82f338
* Type: text
* Required: true
    */
                readonly subheadline: Elements.TextElement;

/*
    * Hero Image
    *
    * Codename: hero_image
* Id: 5030bc21-47d3-451f-b5e7-d59d8d7a2439
* Type: asset
* Required: true
    */
                readonly hero_image: Elements.AssetsElement;

/*
    * Body Copy
    *
    * Codename: body_copy
* Id: 7b9826ff-5cb0-450f-b16a-bd176aed04cf
* Type: rich_text
* Required: false
* Allowed content types: video, disclaimer, call_to_action
    */
                readonly body_copy: Elements.RichTextElement<VideoType | DisclaimerType | CallToActionType>;

/*
    * Webinars
    *
    * Codename: webinars
* Id: 921742ec-fe00-43e4-ac51-b33375521529
* Type: modular_content
* Required: true
* Allowed content types: webinar
    */
                readonly webinars: Elements.LinkedItemsElement<WebinarType>;

/*
    * Homepage CTA Cards
    *
    * Codename: homepage_cta_cards
* Id: 1d5e6895-2272-4206-90eb-54bbd3728892
* Type: modular_content
* Required: true
* Allowed content types: cta_card
    */
                readonly homepage_cta_cards: Elements.LinkedItemsElement<CTACardType>;

/*
    * Featured Blog Posts
    *
    * Codename: featured_blog_posts
* Id: 9049dc0c-b59c-4809-a507-e05b535a9ac7
* Type: modular_content
* Required: false
* Allowed content types: blog_post
    */
                readonly featured_blog_posts: Elements.LinkedItemsElement<BlogPostType>;

/*
    * Featured Content
    *
    * Codename: featured_content
* Id: 38cf004b-3054-43ff-9b7a-f0734b1d35f1
* Type: modular_content
* Required: false
* Allowed content types: event, article, call_to_action
    */
                readonly featured_content: Elements.LinkedItemsElement<EventType | ArticleType | CallToActionType>;

/*
    * Subpages
    *
    * Codename: subpages
* Id: 9d5080db-f2bb-41a1-bcbe-11786ee3a59d
* Type: subpages
* Required: false
* Allowed content types: page
    */
                readonly subpages: Elements.LinkedItemsElement<PageType>;}, 
LandingPageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Landing Page
*/
export type LandingPageTypeElementCodenames = 'headline' | 'subheadline' | 'hero_image' | 'body_copy' | 'webinars' | 'homepage_cta_cards' | 'featured_blog_posts' | 'featured_content' | 'subpages';;

/*
    * Type guard for Landing Page
    *
    * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
* Codename: landing_page
    */
export function isLandingPageType(item: IContentItem | undefined | null): item is LandingPageType {
                return item?.system.type === ('landing_page' satisfies LandingPageTypeCodename);
            };



            