/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Top Banner Ad' type
*/
            export type TopBannerAdTypeCodename = keyof Pick<Record<TypeCodenames, null>, "top_banner_ad">;

            /*
* Typeguard for codename of 'Top Banner Ad' type
*/
            export function isTopBannerAdTypeCodename(value: string | undefined | null): value is TopBannerAdTypeCodename {
                return typeof value === 'string' && value === ('top_banner_ad' satisfies TopBannerAdTypeCodename);
            }

/*
    * Top Banner Ad
    *
    * Id: 474b95c4-282b-4285-9f21-77045ce0ff86
* Codename: top_banner_ad
    */
export type TopBannerAdType = IContentItem<
{
/*
    * Image
    *
    * Codename: image
* Id: 582d83cc-34a0-4223-9ba1-9dc38926c292
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;

/*
    * URL Link
    *
    * Codename: url_link
* Id: 3e056290-6304-4d95-8e29-808a0ea67945
* Type: text
* Required: false
    */
                readonly url_link: Elements.TextElement;}, 
TopBannerAdTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Top Banner Ad
*/
export type TopBannerAdTypeElementCodenames = 'image' | 'url_link';;

/*
    * Type guard for Top Banner Ad
    *
    * Id: 474b95c4-282b-4285-9f21-77045ce0ff86
* Codename: top_banner_ad
    */
export function isTopBannerAdType(item: IContentItem | undefined | null): item is TopBannerAdType {
                return item?.system.type === ('top_banner_ad' satisfies TopBannerAdTypeCodename);
            };



            