/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { AudienceSnippet } from '../snippets/audience-snippet.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Webinar' type
*/
            export type WebinarTypeCodename = keyof Pick<Record<TypeCodenames, null>, "webinar">;

            /*
* Typeguard for codename of 'Webinar' type
*/
            export function isWebinarTypeCodename(value: string | undefined | null): value is WebinarTypeCodename {
                return typeof value === 'string' && value === ('webinar' satisfies WebinarTypeCodename);
            }

/*
    * Webinar
    *
    * Id: ff2b56e3-477a-4e31-bfa2-655522f584c1
* Codename: webinar
    */
export type WebinarType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 4f1d0c6f-1601-4ca5-8d43-89285b1a7ac8
* Type: text
* Required: false
    */
                readonly title: Elements.TextElement;

/*
    * Webinar Description
    *
    * Codename: webinar_description
* Id: e645a37e-188a-4a26-af8f-e2233505646d
* Type: rich_text
* Required: false
    */
                readonly webinar_description: Elements.RichTextElement<CoreType>;

/*
    * Registration Link
    *
    * Codename: registration_link
* Id: be88364a-bd80-4b70-a4ba-b4a7c2f596d3
* Type: text
* Required: false
    */
                readonly registration_link: Elements.TextElement;

/*
    * Webinar Date and Time
    *
    * Codename: webinar_date_and_time
* Id: f654b842-1602-45d8-95ab-45af79a44ef4
* Type: date_time
* Required: false
    */
                readonly webinar_date_and_time: Elements.DateTimeElement;} & AudienceSnippet, 
WebinarTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Webinar
*/
export type WebinarTypeElementCodenames = 'title' | 'webinar_description' | 'registration_link' | 'webinar_date_and_time' | 'audience__audience' | 'audience__offerings';;

/*
    * Type guard for Webinar
    *
    * Id: ff2b56e3-477a-4e31-bfa2-655522f584c1
* Codename: webinar
    */
export function isWebinarType(item: IContentItem | undefined | null): item is WebinarType {
                return item?.system.type === ('webinar' satisfies WebinarTypeCodename);
            };



            