/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'German (de-DE)' language
*/
            export type GermanDeDELanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "de-DE">;

            /*
* Typeguard for codename of 'German (de-DE)' language
*/
            export function isGermanDeDELanguageCodename(value: string | undefined | null): value is GermanDeDELanguageCodename {
                return typeof value === 'string' && value === ('de-DE' satisfies GermanDeDELanguageCodename);
            }
            