/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'Spanish (es-ES)' language
*/
            export type SpanishEsESLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "es-ES">;

            /*
* Typeguard for codename of 'Spanish (es-ES)' language
*/
            export function isSpanishEsESLanguageCodename(value: string | undefined | null): value is SpanishEsESLanguageCodename {
                return typeof value === 'string' && value === ('es-ES' satisfies SpanishEsESLanguageCodename);
            }
            