/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'Spanish (es-ES)' language
*/
            export type SpanishEsESLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "es-ES">;

            /*
* Typeguard for codename of 'Spanish (es-ES)' language
*/
            export function isSpanishEsESLanguageCodename(value: string | undefined | null): value is SpanishEsESLanguageCodename {
                return typeof value === 'string' && value === ('es-ES' satisfies SpanishEsESLanguageCodename);
            }
            