/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Article Type' taxonomy
*/
            export type ArticleTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "article_type">;

            /*
* Typeguard for codename of 'Article Type' taxonomy
*/
            export function isArticleTypeTaxonomyCodename(value: string | undefined | null): value is ArticleTypeTaxonomyCodename {
                return typeof value === 'string' && value === ('article_type' satisfies ArticleTypeTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const articleTypeTaxonomyTermCodenames = ['clinical_guidelines', 'case_study', 'research', 'healthcare_policy_update', 'institutional_announcement', 'industry_updates', 'patient_education', 'professional_training', 'educational'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type ArticleTypeTaxonomyTermCodenames = typeof articleTypeTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isArticleTypeTaxonomyTermCodename(value: string | undefined | null): value is ArticleTypeTaxonomyTermCodenames {
                return typeof value === 'string' && (articleTypeTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            