/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Audience' taxonomy
*/
            export type AudienceTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "audience">;

            /*
* Typeguard for codename of 'Audience' taxonomy
*/
            export function isAudienceTaxonomyCodename(value: string | undefined | null): value is AudienceTaxonomyCodename {
                return typeof value === 'string' && value === ('audience' satisfies AudienceTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const audienceTaxonomyTermCodenames = ['librarians', 'teachers', 'administrators', 'curriculum_specialists', 'parents', 'publisher'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type AudienceTaxonomyTermCodenames = typeof audienceTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isAudienceTaxonomyTermCodename(value: string | undefined | null): value is AudienceTaxonomyTermCodenames {
                return typeof value === 'string' && (audienceTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            