/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Book Classification' taxonomy
*/
            export type BookClassificationTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "book_classification">;

            /*
* Typeguard for codename of 'Book Classification' taxonomy
*/
            export function isBookClassificationTaxonomyCodename(value: string | undefined | null): value is BookClassificationTaxonomyCodename {
                return typeof value === 'string' && value === ('book_classification' satisfies BookClassificationTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const bookClassificationTaxonomyTermCodenames = ['history', 'philosophy', 'business', 'memoir', 'true_crime', 'sports', 'nonfiction', 'mystery_thriller', 'fantasy', 'science_fiction', 'dystopian', 'romance', 'horror', 'adventure', 'historical_fiction', 'self_help', 'easy', 'manga', 'graphic_novel', 'fiction'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type BookClassificationTaxonomyTermCodenames = typeof bookClassificationTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isBookClassificationTaxonomyTermCodename(value: string | undefined | null): value is BookClassificationTaxonomyTermCodenames {
                return typeof value === 'string' && (bookClassificationTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            