/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Book Audience' taxonomy
*/
            export type BookAudienceTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "book_audience">;

            /*
* Typeguard for codename of 'Book Audience' taxonomy
*/
            export function isBookAudienceTaxonomyCodename(value: string | undefined | null): value is BookAudienceTaxonomyCodename {
                return typeof value === 'string' && value === ('book_audience' satisfies BookAudienceTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const bookAudienceTaxonomyTermCodenames = ['lower_elementary', 'upper_elementary', 'middle_school', 'young_adult', 'adult', 'professional'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type BookAudienceTaxonomyTermCodenames = typeof bookAudienceTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isBookAudienceTaxonomyTermCodename(value: string | undefined | null): value is BookAudienceTaxonomyTermCodenames {
                return typeof value === 'string' && (bookAudienceTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            