/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'General Healthcare Topics' taxonomy
*/
            export type GeneralHealthcareTopicsTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "general_healthcare_topics">;

            /*
* Typeguard for codename of 'General Healthcare Topics' taxonomy
*/
            export function isGeneralHealthcareTopicsTaxonomyCodename(value: string | undefined | null): value is GeneralHealthcareTopicsTaxonomyCodename {
                return typeof value === 'string' && value === ('general_healthcare_topics' satisfies GeneralHealthcareTopicsTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const generalHealthcareTopicsTaxonomyTermCodenames = ['healthcare_policy___regulations', 'medical_research___innovations', 'health___wellness', 'preventative_care', 'public_health'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type GeneralHealthcareTopicsTaxonomyTermCodenames = typeof generalHealthcareTopicsTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isGeneralHealthcareTopicsTaxonomyTermCodename(value: string | undefined | null): value is GeneralHealthcareTopicsTaxonomyTermCodenames {
                return typeof value === 'string' && (generalHealthcareTopicsTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            