/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Offerings' taxonomy
*/
            export type OfferingsTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "offerings">;

            /*
* Typeguard for codename of 'Offerings' taxonomy
*/
            export function isOfferingsTaxonomyCodename(value: string | undefined | null): value is OfferingsTaxonomyCodename {
                return typeof value === 'string' && value === ('offerings' satisfies OfferingsTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const offeringsTaxonomyTermCodenames = ['classroom', 'curriculum', 'library', 'professional_development', 'textbooks', 'services'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type OfferingsTaxonomyTermCodenames = typeof offeringsTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isOfferingsTaxonomyTermCodename(value: string | undefined | null): value is OfferingsTaxonomyTermCodenames {
                return typeof value === 'string' && (offeringsTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            