/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Topic' taxonomy
*/
            export type TopicTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "topic">;

            /*
* Typeguard for codename of 'Topic' taxonomy
*/
            export function isTopicTaxonomyCodename(value: string | undefined | null): value is TopicTaxonomyCodename {
                return typeof value === 'string' && value === ('topic' satisfies TopicTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const topicTaxonomyTermCodenames = ['advocacy', 'book_series', 'classroom_book_a_day', 'corporate_social_responsibility', 'diversity', 'early_learning', 'elearning', 'funding', 'genre', 'ib', 'international', 'private___parochial', 'student_wellbeing', 'striving_readers'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type TopicTaxonomyTermCodenames = typeof topicTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isTopicTaxonomyTermCodename(value: string | undefined | null): value is TopicTaxonomyTermCodenames {
                return typeof value === 'string' && (topicTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            