/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Biographies' workflow
*/
            export type BiographiesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "biographies">;

            /*
* Typeguard for codename of 'Biographies' workflow
*/
            export function isBiographiesWorkflowCodename(value: string | undefined | null): value is BiographiesWorkflowCodename {
                return typeof value === 'string' && value === ('biographies' satisfies BiographiesWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const biographiesWorkflowStepCodenames = ['draft_97d445e', 'staff_member_review', 'reviewed_1778942', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type BiographiesWorkflowStepCodenames = typeof biographiesWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isBiographiesWorkflowStepCodename(value: string | undefined | null): value is BiographiesWorkflowStepCodenames {
                return typeof value === 'string' && (biographiesWorkflowStepCodenames as readonly string[]).includes(value);
            };
            