/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Librarian Resources' workflow
*/
            export type LibrarianResourcesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "patient_resources">;

            /*
* Typeguard for codename of 'Librarian Resources' workflow
*/
            export function isLibrarianResourcesWorkflowCodename(value: string | undefined | null): value is LibrarianResourcesWorkflowCodename {
                return typeof value === 'string' && value === ('patient_resources' satisfies LibrarianResourcesWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const librarianResourcesWorkflowStepCodenames = ['draft_b242d4d', 'legal_review', 'marketing_review', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type LibrarianResourcesWorkflowStepCodenames = typeof librarianResourcesWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isLibrarianResourcesWorkflowStepCodename(value: string | undefined | null): value is LibrarianResourcesWorkflowStepCodenames {
                return typeof value === 'string' && (librarianResourcesWorkflowStepCodenames as readonly string[]).includes(value);
            };
            