/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Patient Resources' workflow
*/
            export type PatientResourcesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "patient_resources">;

            /*
* Typeguard for codename of 'Patient Resources' workflow
*/
            export function isPatientResourcesWorkflowCodename(value: string | undefined | null): value is PatientResourcesWorkflowCodename {
                return typeof value === 'string' && value === ('patient_resources' satisfies PatientResourcesWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const patientResourcesWorkflowStepCodenames = ['draft_b242d4d', 'medical_review', 'legal_review', 'marketing_review', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type PatientResourcesWorkflowStepCodenames = typeof patientResourcesWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isPatientResourcesWorkflowStepCodename(value: string | undefined | null): value is PatientResourcesWorkflowStepCodenames {
                return typeof value === 'string' && (patientResourcesWorkflowStepCodenames as readonly string[]).includes(value);
            };
            