/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all collection codenames
*/
            export const collectionCodenames = ['academic_content', 'default', 'operations', 'patient_resources', 'marketing_resources'] as const;;
           
            /*
* Type representing all collection codenames
*/
            export type CollectionCodenames = typeof collectionCodenames[number];;

            /*
* Typeguard for collection codename
*/
            export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
                return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
            };