/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all collection codenames
*/
            export const collectionCodenames = ['default', 'academic_content', 'patient_resources', 'operations'] as const;;
           
            /*
* Type representing all collection codenames
*/
            export type CollectionCodenames = typeof collectionCodenames[number];;

            /*
* Typeguard for collection codename
*/
            export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
                return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
            };