/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all element codenames
*/
            export const elementCodenames = ['title', 'image', 'body', 'offerings', 'topic', 'audience', 'metadata__title', 'metadata__keywords', 'metadata__description', 'url_slug', 'headline', 'subheadline', 'hero_image', 'body_copy', 'webinars', 'homepage_cta_cards', 'featured_blog_posts', 'featured_content', 'subpages', 'name', 'summary', 'description', 'team', 'medical_specialties', 'image_position', 'button_label', 'button_link', 'url', 'link_text', 'page_link', 'outside_url', 'audience__audience', 'audience__offerings', 'url_link', 'start_date', 'end_date', 'event_type', 'event_topic', 'first_name', 'last_name', 'prefix', 'suffixes', 'biography', 'job_title', 'phone', 'email', 'website', 'video_link', 'caption', 'autoplay', 'webinar_description', 'registration_link', 'webinar_date_and_time', 'type', 'publish_date', 'introduction', 'author', 'article_type', 'topics', 'related_articles', 'book_overview', 'cover', 'page_count', 'book_audience', 'book_classification', 'publisher', 'format'] as const;;
           
            /*
* Type representing all element codenames
*/
            export type ElementCodenames = typeof elementCodenames[number];;

            /*
* Typeguard for element codename
*/
            export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
                return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
            };