/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: BCBSA 🏥 🔵
 * Environment: Production
 * Id: 9da2775f-eede-00c1-d7ce-96bf2cae2fed
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all language codenames
*/
            export const languageCodenames = ['default', 'es-ES', 'de-DE'] as const;;
           
            /*
* Type representing all language codenames
*/
            export type LanguageCodenames = typeof languageCodenames[number];;

            /*
* Typeguard for language codename
*/
            export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
                return typeof value === 'string' && (languageCodenames as readonly string[]).includes(value);
            };