/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all language codenames
*/
            export const languageCodenames = ['default', 'es-ES', 'de-DE'] as const;;
           
            /*
* Type representing all language codenames
*/
            export type LanguageCodenames = typeof languageCodenames[number];;

            /*
* Typeguard for language codename
*/
            export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
                return typeof value === 'string' && (languageCodenames as readonly string[]).includes(value);
            };