/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


              import type { IDeliveryClient } from '@kontent-ai/delivery-sdk';
                import type { CollectionCodenames } from './collections.generated.js';
import type { LanguageCodenames } from './languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from './workflows.generated.js';
import type { TaxonomyCodenames } from './taxonomies.generated.js';
import type { TypeCodenames, CoreType } from './types.generated.js';
import type { ElementCodenames } from './elements.generated.js';          

                /*
* Core types for 'IDeliveryClient'
*/
                export type CoreClientTypes = {
                    readonly collectionCodenames: CollectionCodenames;
                    readonly contentItemType: CoreType;
                    readonly contentTypeCodenames: TypeCodenames;
                    readonly elementCodenames: ElementCodenames;
                    readonly languageCodenames: LanguageCodenames;
                    readonly taxonomyCodenames: TaxonomyCodenames;
                    readonly workflowCodenames: WorkflowCodenames;
                    readonly workflowStepCodenames: WorkflowStepCodenames;
                };

                /*
* Typed delivery client. Use this instead of 'IDeliveryClient'
*/
                export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>;
            