/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all snippet codenames
*/
            export const snippetCodenames = ['metadata', 'audience'] as const;;
           
            /*
* Type representing all snippet codenames
*/
            export type SnippetCodenames = typeof snippetCodenames[number];;

            /*
* Typeguard for snippet codename
*/
            export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
                return typeof value === 'string' && (snippetCodenames as readonly string[]).includes(value);
            };