/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Follett Content
 * Environment: Production
 * Id: 0537e98b-379f-0050-5134-9e8d9c775098
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all taxonomy codenames
*/
            export const taxonomyCodenames = ['general_healthcare_topics', 'article_type', 'medical_specialties', 'book_audience', 'offerings', 'topic', 'event_type', 'event_topic', 'audience', 'book_classification'] as const;;
           
            /*
* Type representing all taxonomy codenames
*/
            export type TaxonomyCodenames = typeof taxonomyCodenames[number];;

            /*
* Typeguard for taxonomy codename
*/
            export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
                return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
            };